importando Pandas e printando a soma de nulls

In [92]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import KNNImputer

In [93]:
df = pd.read_csv('winedataset_modified.csv.xls')
df.isnull().sum()
df.isnull()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,False,False,False,False,False,False,False,False,False,False,False,False,False
1595,False,False,False,False,False,False,False,False,False,False,False,False,False
1596,False,False,False,False,False,False,False,False,False,False,False,False,False
1597,False,False,False,False,False,False,False,False,False,False,False,False,False
1598,False,False,False,False,False,False,False,False,False,False,False,False,False

selecionando linhas null

In [94]:
df_filtra_null = df[df.isnull().any(axis=1)]
df_filtra_null

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,red,NaN,0.760,0.04,2.30,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
33,red,6.9,NaN,0.12,NaN,0.073,40.0,83.0,0.99930,3.45,0.52,9.4,6
44,red,6.8,0.670,0.02,1.80,0.050,5.0,11.0,0.99620,NaN,0.52,9.5,5
102,red,NaN,0.545,0.18,1.90,0.080,13.0,35.0,0.99720,3.30,0.59,9.0,6
124,NaN,7.8,0.500,0.17,1.60,0.082,21.0,102.0,0.99600,3.39,0.48,9.5,5
194,red,NaN,0.550,0.21,2.20,0.071,7.0,28.0,0.99640,3.28,0.55,9.7,5
211,red,8.0,0.725,0.24,2.80,0.083,10.0,62.0,0.99685,NaN,0.56,10.0,6
248,red,NaN,0.530,0.06,1.70,0.074,9.0,39.0,0.99615,3.35,0.48,9.8,6
258,red,7.7,NaN,0.76,1.80,0.611,8.0,45.0,0.99680,3.06,1.26,9.4,5
280,red,11.4,NaN,0.44,3.60,0.071,6.0,19.0,0.99860,3.12,0.82,9.3,6
350,NaN,10.7,0.670,0.22,2.70,0.107,17.0,34.0,1.00040,3.28,0.98,9.9,6
358,red,11.9,0.430,0.66,3.10,0.109,10.0,23.0,1.00000,3.15,NaN,10.4,7
368,red,10.3,0.340,0.52,2.80,0.159,15.0,75.0,0.99980,NaN,0.64,9.4,5
398,red,11.5,0.590,NaN,2.60,0.087,13.0,49.0,0.99880,3.18,0.65,11.0,6
485,red,10.2,NaN,0.39,1.90,0.054,6.0,17.0,0.99760,3.17,0.47,10.0,5
503,red,10.5,0.260,0.47,1.90,0.078,6.0,24.0,0.99760,3.18,NaN,10.9,7
530,red,9.1,0.220,0.24,2.10,0.078,1.0,28.0,0.99900,NaN,0.87,10.3,6
555,red,15.5,NaN,0.49,4.20,0.095,10.0,23.0,1.00315,2.92,0.74,11.1,5
573,red,10.5,0.590,NaN,2.10,0.070,14.0,47.0,0.99910,3.30,0.56,9.6,4
596,red,12.4,0.400,0.51,2.00,0.059,6.0,24.0,0.99940,NaN,0.60,9.3,6
602,red,NaN,0.835,0.00,2.60,0.081,6.0,14.0,0.99750,3.30,0.52,9.3,5
677,red,8.6,0.800,0.11,2.30,0.084,12.0,31.0,0.99790,NaN,0.48,9.9,5
678,red,8.3,0.780,0.10,2.60,0.081,45.0,87.0,0.99830,NaN,0.53,10.0,5
682,NaN,8.5,0.460,0.31,2.25,0.078,32.0,58.0,0.99800,3.33,0.54,9.8,5
684,red,9.8,0.980,0.32,2.30,0.078,35.0,152.0,0.99800,3.25,NaN,9.4,5
724,red,7.5,1.115,0.10,3.10,0.086,5.0,12.0,0.99580,NaN,0.60,11.2,4
749,red,7.3,0.510,0.18,2.10,NaN,12.0,28.0,0.99768,3.52,0.73,9.5,6
770,red,NaN,0.590,0.02,2.30,0.082,24.0,94.0,0.99744,3.55,0.53,9.7,6
803,NaN,7.7,0.560,0.08,2.50,0.114,14.0,46.0,0.99710,3.24,0.66,9.6,6
887,red,NaN,0.520,0.38,2.60,0.066,29.0,56.0,0.99577,3.15,0.79,12.1,7
927,red,NaN,0.670,0.19,2.20,0.093,11.0,75.0,0.99736,3.20,0.59,9.2,4
946,red,10.2,0.440,0.58,4.10,0.092,11.0,24.0,0.99745,NaN,0.99,12.0,7
947,red,8.3,NaN,0.48,2.10,0.093,6.0,12.0,0.99408,3.26,0.62,12.4,7
1003,red,NaN,0.360,0.32,1.80,0.067,4.0,8.0,0.99280,3.36,0.55,12.8,7
1110,red,8.3,0.530,0.00,NaN,0.070,6.0,14.0,0.99593,3.25,0.64,10.0,6
1247,red,7.4,0.550,NaN,1.80,0.082,15.0,34.0,0.99655,3.49,0.68,10.5,5
1249,red,7.1,NaN,0.01,2.30,0.079,24.0,37.0,0.99514,3.40,0.61,10.9,6
1315,red,7.5,0.630,0.27,2.00,NaN,17.0,91.0,0.99616,3.26,0.58,9.8,6
1326,NaN,6.7,0.460,0.24,1.70,0.077,18.0,34.0,0.99480,3.39,0.60,10.6,6
1406,red,8.2,NaN,0.34,5.10,0.062,8.0,22.0,0.99740,3.22,0.94,10.9,6
1461,red,6.2,0.785,0.00,2.10,0.060,6.0,13.0,0.99664,3.59,NaN,10.0,4
1467,red,NaN,1.040,0.08,2.30,0.067,19.0,32.0,0.99648,3.52,0.57,11.0,4

esquecendo linhas com valores null

In [95]:
df_drop_linhas = df.dropna()
print(df_drop_linhas.isnull().sum())
#print(df_drop_linhas)

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

esquecendo colunas com valores null

In [96]:
df_drop_colunas = df.drop(columns=['type','fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','pH','sulphates'])
df_drop_colunas.isnull().sum()
df_drop_colunas

      free sulfur dioxide  total sulfur dioxide  density  alcohol  quality
0                    11.0                  34.0  0.99780      9.4        5
1                    25.0                  67.0  0.99680      9.8        5
2                    15.0                  54.0  0.99700      9.8        5
3                    17.0                  60.0  0.99800      9.8        6
4                    11.0                  34.0  0.99780      9.4        5
...                   ...                   ...      ...      ...      ...
1594                 32.0                  44.0  0.99490     10.5        5
1595                 39.0                  51.0  0.99512     11.2        6
1596                 29.0                  40.0  0.99574     11.0        6
1597                 32.0                  44.0  0.99547     10.2        5
1598                 18.0                  42.0  0.99549     11.0        6

[1599 rows x 5 columns]

exibindo os detalhes do dataframe original,dataframe sem linhas com null,sem colunas com null

In [97]:
print("Dataframe", df.shape)
print("Dataframe orginal, sem linha com null,sem linhas com null", df_drop_linhas.shape)
print("Dataframe original, sem colunas com null", df_drop_colunas.shape)

Dataframe (1599, 13)
Dataframe orginal, sem linha com null,sem linhas com null (1557, 13)
Dataframe original, sem colunas com null (1599, 5)

In [98]:
df.to_csv('original.csv', index=False)
df_drop_linhas.to_csv('semLinhas.csv',index=False)
df_drop_colunas.to_csv('semColuna.csv', index=False)

trocado null por media

In [99]:
df[df.index==2]

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,red,NaN,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5

In [100]:
df_media = df.fillna(df.mean(numeric_only=True))
df_media[df_media.index==2]

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,red,8.32253,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5

trocando null por mediana

In [101]:
df_mediana= df.fillna(df.median(numeric_only=True))
df_mediana[df_mediana.index==2]

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,red,7.9,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5

trocando null por moda

In [102]:
df[df.index==124]

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
124,NaN,7.8,0.5,0.17,1.6,0.082,21.0,102.0,0.996,3.39,0.48,9.5,5

In [103]:
dfNovo=df
dfNovo['type'] = dfNovo['type'].fillna (dfNovo['type'].mode()[0])
dfNovo[dfNovo.index==124]

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
124,red,7.8,0.5,0.17,1.6,0.082,21.0,102.0,0.996,3.39,0.48,9.5,5

In [104]:
df2 = df.drop(columns='type')
colunas_faltando = df2.columns[df2.isna().any()].tolist()
sem_colunas_faltando = list(set(df2.columns)-set(colunas_faltando))
sem_colunas_faltando

['total sulfur dioxide',
 'quality',
 'alcohol',
 'density',
 'free sulfur dioxide']

In [105]:
for coluna in colunas_faltando:
    df_temp = df2.dropna()
    X = df_temp[sem_colunas_faltando]
    y = df_temp[coluna]

    regressaoLinear = LinearRegression()
    regressaoLinear.fit(X,y)

    df2.loc[df2[coluna].isna(),coluna]=regressaoLinear.predict(df2.loc[df[coluna].isna(), sem_colunas_faltando])

In [106]:
df[df.index==2]

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,red,NaN,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5

In [107]:
df3 =  df.drop(columns='type')
imputer = KNNImputer(n_neighbors=5)

df3 = pd.DataFrame(imputer.fit_transform(df3),columns=df3.columns)
df3[df3.index==2]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,8.52,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5.0